options:
  debug:
    type: boolean
    default: false
    description: >-
      'Enable/disable nhc debug logging.'
  nhc-config:
    type: string
    default: ""
    description: >-
      'User supplied nhc confinguration'
  health-check-interval:
    type: string
    default: "30"
    description: >-
      'The interval in seconds between executions of HealthCheckProgram.
       The default value is zero, which disables execution.'
  health-check-node-state:
    type: string
    default: "ALL"
    description: >-
      'Identify what node states should execute the HealthCheckProgram.
       Multiple state values may be specified with a comma separator.
       The default value is ANY to execute on nodes in any state.'
